from tkinter import *
from PIL import ImageTk,Image
import tkinter.messagebox as messagebox
import mysql.connector as mysql
root1=Tk()
root1.geometry("500x500")
root1.title("Welcome page")
img=ImageTk.PhotoImage(Image.open("C:\\Users\\Dell\\python\\project\\LOGO.jpg"))
panel=Label(root1,image=img)
panel.image=img
panel.place(x=0,y=0)
def start():
    def insert():
        id1=staff_id.get()
        fname1=fname.get()
        lname1=lname.get()
        email1=email.get()
        phone1=mobile.get()
        dob1=dob.get()
        doj1=doj.get()
        salary1=basic_salary.get()
        if (id1=="" or fname1=="" or lname1=="" or email1=="" or phone1=="" or dob1=="" or doj1=="" or
        salary1==""):
            messagebox.showinfo("Insert status","All fills are required")
        else:
            con=mysql.connect(host="localhost",user="root",passwd="vineetsharma",database="project")
            cur=con.cursor()
            cur.execute("insert into staff values
            ('"+id1+"','"+fname1+"','"+lname1+"','"+email1+"','"+phone1+"','"+dob1+"','"+doj1+"','"+salary1+"')")  cur.execute("commit")
            staff_id.delete(0,"end")
            fname.delete(0,"end")
            lname.delete(0,"end")
            email.delete(0,"end")
            mobile.delete(0,"end")
            dob.delete(0,"end")
            doj.delete(0,"end")
            basic_salary.delete(0,"end")
            messagebox.showinfo("Insert status","Inserted successfully")
            con.close()
    def delete():
        
        if(staff_id.get()==""):
            messagebox.showinfo("Delete status","ID is compulsary for delete")
        else:
            con=mysql.connect(host="localhost",user="root",passwd="vineetsharma",database="project")
            cur=con.cursor()
            cur.execute("delete from staff where staff_id='"+staff_id.get()+"'")
            cur.execute("commit")
            staff_id.delete(0,"end")
            fname.delete(0,"end")
            lname.delete(0,"end")
            email.delete(0,"end")
            mobile.delete(0,"end")
            dob.delete(0,"end")
            doj.delete(0,"end")
            basic_salary.delete(0,"end")
            messagebox.showinfo("Insert status","Deleted successfully")
            con.close()
    def update():
        id1=staff_id.get()
        fname1=fname.get()
        lname1=lname.get()
        email1=email.get()
        phone1=mobile.get()
        dob1=dob.get()
        doj1=doj.get()
        salary1=basic_salary.get()

        if (id1==" " or fname1==" " or lname1==" " or email1==" " or phone1==" " or dob1==" " or doj1==" " or salary1==" "):
            messagebox.showinfo("update status","All fills are required")
        else:
            con=mysql.connect(host="localhost",user="root",passwd="vineetsharma",database="project")
            cur=con.cursor()
            update="update staff set
            fname='%s',lname='%s',email='%s',mobile='%s',dob='%s',doj='%s',basic_salary='%s' where
            staff_id='%s'"%(fname1,lname1,email1,phone1,dob1,doj1,salary1,id1)

            cur.execute(update)
            cur.execute("commit")
            staff_id.delete(0,"end")
            fname.delete(0,"end")
            lname.delete(0,"end")
            email.delete(0,"end")
            mobile.delete(0,"end")
            dob.delete(0,"end")
            doj.delete(0,"end")
            basic_salary.delete(0,"end")
            messagebox.showinfo("update status","updated successfully")
            con.close()
    def search():
        if(staff_id.get()==" "):
            messagebox.showinfo("Fetch status","ID is compulsary for delete")
        else:
            con=mysql.connect(host="localhost",user="root",passwd="vineetsharma",database="project")
            cur=con.cursor()
            cur.execute("select* from staff where staff_id='"+staff_id.get()+"'")
            rows=cur.fetchall()
            for i in rows:
            fname.insert(0,i[1])
            lname.insert(0,i[2])
            email.insert(0,i[3])
            mobile.insert(0,i[4])
            dob.insert(0,i[5])
            doj.insert(0,i[6])
            basic_salary.insert(0,i[7])
        con.close()
    def show():
        root=Tk()
        root.geometry("600x300")
        root.title("Program")
        con=mysql.connect(host="localhost",user="root",passwd="vineetsharma",database="project")
        cur=con.cursor()
        cur.execute("select* from staff")
        rows=cur.fetchall()
        list=Listbox(root,bd=1,height=10,width=80)
        list.place(x=30,y=30)
        for i in rows:
            insertdata=str(i[0])+" "+i[1]+" "+i[2]+" "+i[3]+" "+i[4]+" "+str(i[5])+" "+str(i[6])+" "+str(i[7])
            list.insert(list.size()+1,insertdata)
        con.close()
    def exit():
        root.destroy()

    root=Tk()
    root.geometry("900x500")
    root.title("Program")
    lbl=Label (root,text="Staff Management System",font=('Times New Roman',30,'bold'))
    lbl.place(x=250,y=30)
    lbl1=Label(root,text="=============================================",font=('Times New
    Roman',21,'bold'))
    lbl1.place(x=00,y=90)

    id=Label (root,text="Enter Id",font=('arail',15,'bold'))
    id.place(x=50,y=120)
    fname=Label (root,text="Enter First name",font=('arail',15,'bold'))
    fname.place(x=50,y=150)
    lname=Label (root,text="Enter Last name",font=('arail',15,'bold'))
    lname.place(x=50,y=180)
    email=Label (root,text="Enter email",font=('arail',15,'bold'))
    email.place(x=50,y=210)
    phone=Label (root,text="Enter phone no.",font=('arail',15,'bold'))
    phone.place(x=50,y=240)
    dob=Label (root,text="Enter Date of birth",font=('arail',15,'bold'))
    dob.place(x=50,y=270)
    doj=Label (root,text="Enter Date of joining",font=('arail',15,'bold'))
    doj.place(x=50,y=300)
    salary=Label (root,text="Enter salary",font=('arail',15,'bold'))
    salary.place(x=50,y=330)
    staff_id=Entry(root,bd=10)
    staff_id.place(x=500,y=120)
    fname=Entry(root,bd=10)
    fname.place(x=500,y=150)
    lname=Entry(root,bd=10)
    lname.place(x=500,y=180)
    email=Entry(root,bd=10)
    email.place(x=500,y=210)
    mobile=Entry(root,bd=10)
    mobile.place(x=500,y=240)
    dob=Entry(root,bd=10)
    dob.place(x=500,y=270)
    doj=Entry(root,bd=10)
    doj.place(x=500,y=300)
    basic_salary=Entry(root,bd=10)
    basic_salary.place(x=500,y=330)
    insert=Button(root,text="Insert",font=("italic",10,"bold"),bd=10,bg="white",command=insert)
    insert.place(x=200,y=400)
    delete=Button(root,text="Delete",font=("italic",10,"bold"),bd=10,bg="white",command=delete)
    delete.place(x=300,y=400)
    update=Button(root,text="Update",font=("italic",10,"bold"),bd=10,bg="white",command=update)
    update.place(x=400,y=400)
    search=Button(root,text="Search",font=("italic",10,"bold"),bd=10,bg="white",command=search)
    search.place(x=500,y=400)
    show=Button(root,text="Show",font=("italic",10,"bold"),bd=10,bg="white",command=show)
    show.place(x=600,y=400)
    exit=Button(root,text="Exit",font=("italic",10,"bold"),bd=10,bg="white",command=exit)
    exit.place(x=700,y=400)
bt=Button(root1,text="start",font=("italic",10,"bold"),bd=10,bg="white",command=start)
bt.place(x=200,y=450) 
